### ISSUE TITLE
Unraid Docker Container unable to update to the new version (v3.1.2)

### ISSUE THREAD

**Issue by k3sra** [ich777/docker-beamng-mp-server#1]
Server.log:
 [WARN] [33;1mNEW VERSION IS OUT! Please update to the new version (v3.1.2) of the BeamMP-Server! Download it here: https://beammp.com/! For a guide on how to update, visit: https://wiki.beammp.com/en/home/server-maintenance#updating-the-server[0m

Container log after trying to start it:
---Something went wrong, can't download BeamNG-MP-Server v3.2.1, putting container in sleep mode---

**Comment by ich777** [comment]
Please see [this](https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=1341066) post, no issue running the container over here.
```

---Checking if UID: 99 matches user---
usermod: no changes
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 0000---
---Checking for optional scripts---
---No optional script found, continuing---
---Starting...---
---Version Check---
---BeamNG-MP-Server v3.2.1 up-to-date---
---Prepare Server---
---Start Server---
[12/01/24 13:37:16] [INFO] BeamMP Server v3.2.1
[12/01/24 13:37:16] [INFO] Loaded 17 Mods
[12/01/24 13:37:16] [INFO] Vehicle event network online
[12/01/24 13:37:16] [INFO] Vehicle data network online on port 30814 with a Max of 8 Clients
[12/01/24 13:37:16] [INFO] Server up-to-date!
[12/01/24 13:37:16] [INFO] PluginMonitor started
[12/01/24 13:37:21] [INFO] ALL SYSTEMS STARTED SUCCESSFULLY, EVERYTHING IS OKAY
```

**Comment by k3sra** [comment]
Thanks! Works absolutely perfect after deleting the required file.
