### ISSUE TITLE
Unraid Docker Container unable to update to the new version (v3.2.2)

### ISSUE THREAD

**Issue by ilarikokko** [ich777/docker-beamng-mp-server#2]
Hi,

I have the same problem as @K3sra in a issue: https://github.com/ich777/docker-beamng-mp-server/issues/1

![image](https://github.com/ich777/docker-beamng-mp-server/assets/77028448/40700170-525e-46e1-8845-1684ff4aef37)

- I tried to remove the "BeamMP-Server" file in the directory
- I tried to install this in the Docker Desktop enviroment --> Same issue
- Looked in to this post --> https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/page/356/#comment-1341066

The same issue happened before in v3.2.1, but then the server file deletion fixed the issue.

If this happens is it possible manually to download the server file from the BeamMP repo and put it to the directory? What is correct distro?
https://github.com/BeamMP/BeamMP-Server/releases/tag/v3.2.2

**Comment by ich777** [comment]
> The same issue happened before in v3.2.1, but then the server file deletion fixed the issue.

Thank you for the report.
Seems like they changed the naming scheme from the releases.

Please update the container itself by issuing a force update from the Docker page (with advanced view enabled) if you are using Unraid.

**Comment by ilarikokko** [comment]
> > The same issue happened before in v3.2.1, but then the server file deletion fixed the issue.
> 
> Thank you for the report. Seems like they changed the naming scheme from the releases.
> 
> Please update the container itself by issuing a force update from the Docker page (with advanced view enabled) if you are using Unraid.

Hi,

Thank you, after container update its working now. "Normal update" also worked fine.
