### ISSUE TITLE
How can I run server commands?

### ISSUE THREAD

**Issue by Gusfit1** [ich777/docker-beamng-mp-server#3]
I'm trying to configure the [Cobalt Essentials](https://github.com/prestonelam2003/CobaltEssentials) plugin and the instructions mention setting the owner by running `ce setgroup yourName owner` in the server console. I've tried entering this in the console from the drop down menu, along with a few variations with no luck. I've also verified the plugin is active.

Do you know how or where I can input this command?

**Comment by ich777** [comment]
Currently the container isn't designed to run server commands but I will look into that and see if I can add that.
Please give me a bit.

**Comment by ich777** [comment]
@DrDelight I have now implemented a WebConsole, please update the container to the latest version, make sure that your `docker run` command includes something like `-p 9045:8080` and you will be then be able to connect to the WebConsole trough: `IP:9045` (if you are using the container on Unraid, chances may be high that port 8080 is already forwarded and you can connect with `IP:8080` to the WebConsole).

Please let me know how it goes, I'll attach a screenshot from my WebConsole:
![grafik](https://github.com/user-attachments/assets/b1b0ed6d-46e2-4cbe-b164-6fd89582512c)

**Comment by Gusfit1** [comment]
Works perfectly! Thank you.

**Comment by ich777** [comment]
Thanks for confirming, I'll close this issue!
